// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project;

namespace Project.Migrations
{
    [DbContext(typeof(RailDBContext))]
    partial class RailDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GlobalSectionOrganisation", b =>
                {
                    b.Property<int>("GlobalSectionsGlobalSectId")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationsOrganisationId")
                        .HasColumnType("int");

                    b.HasKey("GlobalSectionsGlobalSectId", "OrganisationsOrganisationId");

                    b.HasIndex("OrganisationsOrganisationId");

                    b.ToTable("GlobalSectionOrganisation");
                });

            modelBuilder.Entity("Project.DAL.Models.DefectAudit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfDetection")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefectCode")
                        .HasColumnType("int");

                    b.Property<double>("DefectDepth")
                        .HasColumnType("float");

                    b.Property<double>("DefectLenght")
                        .HasColumnType("float");

                    b.Property<int>("Manufacture")
                        .HasColumnType("int");

                    b.Property<string>("ManufactureYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Path")
                        .HasColumnType("int");

                    b.Property<int>("WaySide")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DefectAudits");
                });

            modelBuilder.Entity("Project.DAL.Models.Defectoscope", b =>
                {
                    b.Property<int>("DefectoScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefectoScopeType")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SubOrgId")
                        .HasColumnType("int");

                    b.HasKey("DefectoScopeId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Defectoscopes");
                });

            modelBuilder.Entity("Project.DAL.Models.Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DefectoScopeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastQualificationTraning")
                        .HasColumnType("datetime2");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("Qualification")
                        .HasColumnType("int");

                    b.Property<int?>("SubOrgId")
                        .HasColumnType("int");

                    b.HasKey("OperatorId");

                    b.HasIndex("DefectoScopeId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Project.Models.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Kilometer")
                        .HasColumnType("int");

                    b.Property<int?>("LocalSectionLocalSectoionId")
                        .HasColumnType("int");

                    b.Property<int>("Pkt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalSectionLocalSectoionId");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("Project.Models.Defect", b =>
                {
                    b.Property<int>("DefectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CoordinateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfDetection")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefectCode")
                        .HasColumnType("int");

                    b.Property<double>("DefectDepth")
                        .HasColumnType("float");

                    b.Property<double>("DefectLenght")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Manufacture")
                        .HasColumnType("int");

                    b.Property<string>("ManufactureYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Path")
                        .HasColumnType("int");

                    b.Property<int>("WaySide")
                        .HasColumnType("int");

                    b.HasKey("DefectId");

                    b.HasIndex("CoordinateId");

                    b.ToTable("Defects");
                });

            modelBuilder.Entity("Project.Models.GlobalSection", b =>
                {
                    b.Property<int>("GlobalSectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GlobaSectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GlobalWayNumber")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int?>("SubOrgId")
                        .HasColumnType("int");

                    b.HasKey("GlobalSectId");

                    b.ToTable("GlobalSections");
                });

            modelBuilder.Entity("Project.Models.LocalSection", b =>
                {
                    b.Property<int>("LocalSectoionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GlobalSectionGlobalSectId")
                        .HasColumnType("int");

                    b.Property<string>("LocaSectionlName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LocalWayNumber")
                        .HasColumnType("int");

                    b.HasKey("LocalSectoionId");

                    b.HasIndex("GlobalSectionGlobalSectId");

                    b.ToTable("LocalSections");
                });

            modelBuilder.Entity("Project.Models.Organisation", b =>
                {
                    b.Property<int>("OrganisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("ParentOrganisationId")
                        .HasColumnType("int");

                    b.Property<int?>("SubOrgId")
                        .HasColumnType("int");

                    b.HasKey("OrganisationId");

                    b.HasIndex("ParentOrganisationId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GlobalSectionOrganisation", b =>
                {
                    b.HasOne("Project.Models.GlobalSection", null)
                        .WithMany()
                        .HasForeignKey("GlobalSectionsGlobalSectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationsOrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.DAL.Models.Defectoscope", b =>
                {
                    b.HasOne("Project.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Project.DAL.Models.Operator", b =>
                {
                    b.HasOne("Project.DAL.Models.Defectoscope", "Defectoscope")
                        .WithMany("Operators")
                        .HasForeignKey("DefectoScopeId");

                    b.HasOne("Project.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defectoscope");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Project.Models.Coordinate", b =>
                {
                    b.HasOne("Project.Models.LocalSection", "LocalSection")
                        .WithMany("Coordinates")
                        .HasForeignKey("LocalSectionLocalSectoionId");

                    b.Navigation("LocalSection");
                });

            modelBuilder.Entity("Project.Models.Defect", b =>
                {
                    b.HasOne("Project.Models.Coordinate", "Coordinate")
                        .WithMany("Defects")
                        .HasForeignKey("CoordinateId");

                    b.Navigation("Coordinate");
                });

            modelBuilder.Entity("Project.Models.LocalSection", b =>
                {
                    b.HasOne("Project.Models.GlobalSection", "GlobalSection")
                        .WithMany("LocalSections")
                        .HasForeignKey("GlobalSectionGlobalSectId");

                    b.Navigation("GlobalSection");
                });

            modelBuilder.Entity("Project.Models.Organisation", b =>
                {
                    b.HasOne("Project.Models.Organisation", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentOrganisationId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.HasOne("Project.Models.Organisation", "Organisation")
                        .WithMany("Users")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Project.DAL.Models.Defectoscope", b =>
                {
                    b.Navigation("Operators");
                });

            modelBuilder.Entity("Project.Models.Coordinate", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("Project.Models.GlobalSection", b =>
                {
                    b.Navigation("LocalSections");
                });

            modelBuilder.Entity("Project.Models.LocalSection", b =>
                {
                    b.Navigation("Coordinates");
                });

            modelBuilder.Entity("Project.Models.Organisation", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
